#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Introduction to C++ and Numerical Methods  # The title of the book. Will be placed in the left navbar.
author                      : William Oquendo  # The author of the book
email                       : wfoquendop@unal.edu.co  # An email address to contact the author
copyright                   : "2024"  # Copyright year to be placed in the footer
logo                        : https://upload.wikimedia.org/wikipedia/commons/1/18/ISO_C%2B%2B_Logo.svg  # A path to the book logo
# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns            : [_build, Thumbs.db, .DS_Store,
"**.ipynb_checkpoints", "VisualizationGL", "00-IntroCourse**", "**.virtual_documents**"]
# Auto-exclude files not in the toc
only_build_toc_files        : true
# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
#######################################################################################
# Execution settings
execute:
  execute_notebooks         : auto  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""    # A path to the jupyter cache that will be used to store execution artifacts. Defaults to `_build/.jupyter_cache/`
  exclude_patterns          : []    # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)
  timeout                   : 40    # The maximum time (in seconds) each notebook cell is allowed to run.
  run_in_temp               : false # If `True`, then a temporary directory will be created and used as the command working directory (cwd),
                                    # otherwise the notebook's parent directory will be the cwd.
  allow_errors              : false # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.
  stderr_output             : show  # One of 'show', 'remove', 'remove-warn', 'warn', 'error', 'severe'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

## Add a bibtex file so that we can create citations
#bibtex_bibfiles:
#  - references.bib

#######################################################################################
# Launch button settings
launch_buttons:
  use_binder_button         : true  # Add a binder button to pages (requires the repository to run on Binder)
  notebook_interface        : jupyterlab  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : "https://mybinder.org"  # The URL of the BinderHub (e.g., https://mybinder.org)
  binder_repo_base          : "https://github.com/"  # The site on which the textbook repository is hosted
  binder_repo_org           : "iluvatar1"  # The username or organization that owns this repository
  binder_repo_name          : "ProgCPP-lectures-jupyter"  # The name of the repository on the web
  binder_repo_branch        : "gh-pages"  # The branch on which your textbook is hosted.
  binderhub_interact_text   : "Interact"  # The text that interact buttons will contain.
  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                 : "https://colab.research.google.com/github/iluvatar1/ProgCPP-lectures-jupyter/blob/master" # The URL of Google Colab (https://colab.research.google.com)
# Information about where the book exists on the web
repository:
  url: https://github.com/iluvatar1/ProgCPP-lectures-jupyter  # Online location of your book
  #path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

# Parsing math blocks
parse:
  myst_enable_extensions: ["dollarmath", "amsmath", "html_image"]
# Displaying interactive plotly figures
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
