name: deploy-book
on:
  push:
    branches:
      - master
env:
  BASE_URL: /${{ github.event.repository.name || 'local-test' }}
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build the book
        run: |
          jupyter-book build .

      # For GitHub environment - actual deployment
      - name: Deploy to GitHub Pages
        if: ${{ !env.ACT }}
        uses: peaceiris/actions-gh-pages@v3.5.9
        with:
          personal_token: ${{ secrets.ACTIONS_FOR_BOOK_ACCESS_TOKEN }}
          publish_dir: ./_build/html
          publish_branch: gh-pages

      # For local testing - just verify the build
      - name: Local build verification
        if: ${{ env.ACT }}
        run: |
          echo "🚀 Local build verification completed!"
          echo "✓ Book built successfully in ./_build/html"
          echo "📚 Contents of build directory:"
          ls -la ./_build/html
          echo ""
          echo "ℹ️  Note: Running in local environment - skipping gh-pages deployment"
          echo "   When this runs on GitHub, content will be deployed to gh-pages branch"
